baseURL = "https://joshuacrewe.github.io/"
canonifyurls = true
languageCode = "en-us"
theme = "casper"
title = "Simon Crewe"
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[params.social]
[params]
  description = "Forensic Odontologist"
