baseURL = "http://simoncrewe.co.uk/"
canonifyurls = true
languageCode = "en-us"
theme = "casper"
title = "Simon Crewe"
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 2
[params]
description = "Forensic Odontologist"
[params.social]
